# Generated by Django 5.2.1 on 2025-05-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcard',
            name='guest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='guest_house.guest'),
        ),
    ]
