# Generated by Django 5.2.1 on 2025-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_house', '0002_debitcard_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitcard',
            name='guest',
        ),
        migrations.AddField(
            model_name='debitcard',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
